services:

    #
    # Event Dispatchers
    #
    gearman.dispatcher.abstract:
        abstract: true
        arguments:
            - "@event_dispatcher"

    gearman.dispatcher.callbacks:
        parent: gearman.dispatcher.abstract
        public: true
        class: "%gearman.dispatcher.callbacks.class%"
